// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }


import type { Metadata } from "next";
import { Playfair_Display, Inter, Merriweather_Sans, Gloock } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";

// Elegant Serif font for Headings
const serif = Playfair_Display({ 
  subsets: ["latin"], 
  variable: "--font-serif" 
});

// Clean Sans font for Body text
const sans = Inter({ 
  subsets: ["latin"], 
  variable: "--font-sans" 
});

const merriweather = Merriweather_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-merriweather",
});

const gloock = Gloock({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-gloock",
});

export const metadata: Metadata = {
  title: "Shobha Beauty | Luxury Salon Services",
  description: "Experience premium beauty and hair services.",
};

// Fixed the 'any' type error by defining the type as React.ReactNode
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${serif.variable} ${sans.variable} ${merriweather.variable} ${gloock.variable}`}>
      <body className="font-sans antialiased bg-[#FAF9F6] text-[#1a1a1a]">
        <Navbar />
        <main className="pt-20">
          {children}
        </main>
      </body>
    </html>
  );
}